import React from 'react';
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Link from 'next/link';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Header } from '../components/header';
import { Layout } from '../components/layout';
import NetworkHero from '../components/network-hero';
import {
  PostsByPublicationDocument,
  PostsByPublicationQuery,
  PostsByPublicationQueryVariables,
  PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

const SubscribeForm = dynamic(() =>
  import('../components/subscribe-form').then((mod) => mod.SubscribeForm),
);




// Simple arrow icon component
const ArrowRight = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="w-5 h-5">
    <line x1="5" y1="12" x2="19" y2="12" />
    <polyline points="12 5 19 12 12 19" />
  </svg>
);

type Props = {
  publication: PublicationFragment;
};

const blogCategories = [
  {
    title: "Network Automation",
    description: "Practical guides and tutorials on automating network tasks using Python, Ansible, and more.",
    icon: "🤖"
  },
  {
    title: "Cloud Infrastructure",
    description: "Hands-on labs and best practices for working with AWS, Azure, and GCP.",
    icon: "☁️"
  },
  {
    title: "DevOps Practices",
    description: "Real-world examples of implementing DevOps principles in network operations.",
    icon: "🔄"
  }
];

export default function Index({ publication }: Props) {
  return (
    <AppProvider publication={publication}>
      <Layout>
        <Head>
          <title>{publication.displayTitle || publication.title || 'Network Automation Blog'}</title>
          <meta
            name="description"
            content="Exploring network, automation, cloud infrastructure, and DevOps practices through practical examples and hands-on labs."
          />
          {/* ... rest of the head content ... */}
        </Head>
        <Header />
        <main className="flex-grow">
          {/* Hero Section */}
          <section className="py-16 bg-gradient-to-b from-blue-50 to-white">
            <Container>
              <div className="max-w-3xl mx-auto text-center">
                <h1 className="text-4xl font-bold text-slate-800 mb-6">
                  Simplifying Network, Automation & Cloud Infrastructure
                </h1>
                <p className="text-lg text-slate-600 mb-8">
                  Explore the exciting world of networking through practical tutorials, 
                  hands-on labs, and real-world examples.
                </p>
                <Link href="/blog">
                  <button className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold 
                    hover:bg-blue-500 transition-colors duration-300 flex items-center gap-2 mx-auto">
                    Explore Latest Posts
                    <ArrowRight />
                  </button>
                </Link>
              </div>
            </Container>
          </section>

          {/* Blog Categories Section */}
          <section className="py-16 bg-white">
            <Container>
              <h2 className="text-2xl font-bold text-slate-800 mb-8 text-center">
                What You&apos;ll Learn
              </h2>
              <div className="grid md:grid-cols-3 gap-8">
                {blogCategories.map((category, index) => (
                  <div
                    key={index}
                    className="bg-blue-50 rounded-lg p-6 hover:shadow-md transition-shadow duration-300"
                  >
                    <div className="text-3xl mb-4">{category.icon}</div>
                    <h3 className="text-xl font-semibold mb-3 text-slate-800">
                      {category.title}
                    </h3>
                    <p className="text-slate-600">
                      {category.description}
                    </p>
                  </div>
                ))}
              </div>
            </Container>
          </section>

          {/* Newsletter Section */}
          <section className="py-16 bg-blue-50">
            <Container>
              <div className="max-w-2xl mx-auto text-center">
                <h2 className="text-2xl font-bold text-slate-800 mb-4">
                  Stay Updated
                </h2>
                <p className="text-slate-600 mb-8">
                  Subscribe to receive new tutorials, guides, and automation tips directly in your inbox.
                </p>
                <div className="bg-white rounded-lg p-6 shadow-sm">
                  <SubscribeForm />
                </div>
              </div>
            </Container>
          </section>
        </main>
        <Footer />
      </Layout>
    </AppProvider>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
    GQL_ENDPOINT,
    PostsByPublicationDocument,
    {
      first: 10,
      host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
    },
  );

  const publication = data.publication;
  if (!publication) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      publication,
    },
    revalidate: 1,
  };
};